name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is https://github.com/freddydk/AL-Go@lowhanging)
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'

permissions:
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  UpdateALGoSystemFiles:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@lowhanging
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@lowhanging
        with:
          shell: powershell
          eventId: "DO0098"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@lowhanging
        with:
          shell: powershell
          get: templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@lowhanging
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Override templateUrl
        env:
          templateUrl: ${{ github.event.inputs.templateUrl }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $templateUrl = $ENV:templateUrl
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "templateUrl=$templateUrl"
          }

      - name: Calculate Input
        env:
          directCommit: ${{ github.event.inputs.directCommit }}
          downloadLatest: ${{ github.event.inputs.downloadLatest }}
          eventName: ${{ github.event_name }}
          GhTokenWorkflow: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
        run: |
          $errorActionPreference = "Stop";
          $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $directCommit = $ENV:directCommit
          $downloadLatest = $ENV:downloadLatest
          Write-Host $ENV:eventName
          if ($ENV:eventName -eq 'schedule') {
            $downloadLatest = 'true'
            $directCommit = 'true'
            try {
              Write-Host "Running Update AL-Go System Files on a schedule."
              $ENV:GH_TOKEN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GhTokenWorkflow))
              $rules = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$env:GITHUB_REPOSITORY/rules/branches/$env:GITHUB_REF_NAME | ConvertFrom-Json
              $branchProtection = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$env:GITHUB_REPOSITORY/branches/$env:GITHUB_REF_NAME/protection | ConvertFrom-Json
              if ($rules | Where-Object { $_.type -eq 'pull_request' }) {
                Write-Host "Pull request rule exists for branch $($env:GITHUB_REF_NAME)"
                $directCommit = 'false'
              }
              elseif ($branchProtection.PSObject.Properties.Name -eq "required_pull_request_reviews") {
                Write-Host "Branch protection requires pull request for branch $($env:GITHUB_REF_NAME)"
                if ($branchProtection.enforce_admins.enabled) {
                  $directCommit = 'false'
                }
                else {
                  Write-Host "Update AL-Go System Files will bypass branch protection for branch $($env:GITHUB_REF_NAME)"
                }
              }
              else {
                Write-Host "Pull request not required for branch $($env:GITHUB_REF_NAME)"
              }
            }
            catch {
              Write-Host "Error occurred while checking branch protection for branch $($env:GITHUB_REF_NAME): $_" #test
            }
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update AL-Go system files
        uses: freddydk/AL-Go/Actions/CheckForUpdates@lowhanging
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: ${{ env.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@lowhanging
        with:
          shell: powershell
          eventId: "DO0098"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
